name: challenge_tsoft
description: "Challenge técnico"

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  storybook_flutter: ^0.14.1
  flutter_dotenv: ^5.2.1
  http: ^1.4.0
  shimmer_animation: ^2.2.2
  provider: ^6.1.5

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/section_btn.png
    - assets/icons/categories_btn.png
    - assets/icons/circle_btn.png
    - assets/icons/search_btn.png
    - assets/icons/sort_btn.png
    - assets/icons/eye_movie_item.png
    - assets/icons/arrow_forward.png
    - assets/icons/media_settings.png
    - assets/icons/media_volume.png
    - assets/icons/media_full_screen.png
    - assets/icons/fire.png
    - assets/icons/arrow_down.png
    - assets/images/user_test0.jpg
    - assets/images/user_test1.jpg
    - assets/images/user_test2.jpg
    - .env

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/quicksand/static/Quicksand-Bold.ttf
        - asset: assets/fonts/quicksand/static/Quicksand-Light.ttf
        - asset: assets/fonts/quicksand/static/Quicksand-Medium.ttf
        - asset: assets/fonts/quicksand/static/Quicksand-Regular.ttf
        - asset: assets/fonts/quicksand/static/Quicksand-SemiBold.ttf